### ISSUE TITLE
About the KS spec ...

### ISSUE THREAD

**Issue by KOLANICH** [VincenzoLaSpesa/XiaomiDepthMapExtractor#1]
Hi. I see you have created a Kaitai Struct spec.

1. The file should probably be called `xiaomi_depthmap.ksy`
2. It should be refactored. I have looked into it, but the names of fields are not very meaningful and completely lack docs.
3. Could you send your spec to https://github.com/kaitai-io/kaitai_struct_formats

**Comment by VincenzoLaSpesa** [comment]
Hello.
I agree, the ksy file needs to be refactored.
I'm not happy with it and it's due to the fact that I'm not proficient with the technology ( I'm sure that some of the work I do in C# could be done by Kaitai too ), but also to the fact that I still don't fully understand the format.
I don't know the meaning of most of the parameters inside the file, and I can't still interpret the confidence map.

I will try to refactor it at my best, but I prefer not to send the specs to the repository till they are more stable.

**Comment by KOLANICH** [comment]
>I don't know the meaning of most of the parameters inside the file

The current convention in KSF is to call them `unkn<number>` or `unknown<number>`.

>but I prefer not to send the specs to the repository until they are more stable.

From one side it makes sense, from another one .... KSF is a central hub of formats-related activity in KS projects, so sending there something (
we have 2 kinds: an issue and a PR, issue means an intent to have such a format (anyone can start implementing it), a PR means that its owner is assigned to implementing a format, a draft PR (it is a GitHub feature to mark PRs as ddrafts) means the format is not yet finished, but you can still get feedback!) is very useful to do as early as possible. Because it allows to avoid the situation when 2 different people implement the same thing (it happenned to me once) wasting the effort.

**Comment by VincenzoLaSpesa** [comment]
I've created a draft pr in the repository.
